// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Any;
@class AnyBuilder;



@interface AnyRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Any_type_url @"typeUrl"
#define Any_value @"value"
@interface Any : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTypeUrl_:1;
  BOOL hasValue_:1;
  NSString* typeUrl;
  NSData* value;
}
- (BOOL) hasTypeUrl;
- (BOOL) hasValue;
@property (readonly, strong) NSString* typeUrl;
@property (readonly, strong) NSData* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AnyBuilder*) builder;
+ (AnyBuilder*) builder;
+ (AnyBuilder*) builderWithPrototype:(Any*) prototype;
- (AnyBuilder*) toBuilder;

+ (Any*) parseFromData:(NSData*) data;
+ (Any*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Any*) parseFromInputStream:(NSInputStream*) input;
+ (Any*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Any*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Any*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AnyBuilder : PBGeneratedMessageBuilder {
@private
  Any* resultAny;
}

- (Any*) defaultInstance;

- (AnyBuilder*) clear;
- (AnyBuilder*) clone;

- (Any*) build;
- (Any*) buildPartial;

- (AnyBuilder*) mergeFrom:(Any*) other;
- (AnyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AnyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTypeUrl;
- (NSString*) typeUrl;
- (AnyBuilder*) setTypeUrl:(NSString*) value;
- (AnyBuilder*) clearTypeUrl;

- (BOOL) hasValue;
- (NSData*) value;
- (AnyBuilder*) setValue:(NSData*) value;
- (AnyBuilder*) clearValue;
@end


// @@protoc_insertion_point(global_scope)
