// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Empty.pb.h"
// @@protoc_insertion_point(imports)

@implementation EmptyRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [EmptyRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface Empty ()
@end

@implementation Empty

- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static Empty* defaultEmptyInstance = nil;
+ (void) initialize {
  if (self == [Empty class]) {
    defaultEmptyInstance = [[Empty alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultEmptyInstance;
}
- (instancetype) defaultInstance {
  return defaultEmptyInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (Empty*) parseFromData:(NSData*) data {
  return (Empty*)[[[Empty builder] mergeFromData:data] build];
}
+ (Empty*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Empty*)[[[Empty builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (Empty*) parseFromInputStream:(NSInputStream*) input {
  return (Empty*)[[[Empty builder] mergeFromInputStream:input] build];
}
+ (Empty*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Empty*)[[[Empty builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (Empty*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (Empty*)[[[Empty builder] mergeFromCodedInputStream:input] build];
}
+ (Empty*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (Empty*)[[[Empty builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (EmptyBuilder*) builder {
  return [[EmptyBuilder alloc] init];
}
+ (EmptyBuilder*) builderWithPrototype:(Empty*) prototype {
  return [[Empty builder] mergeFrom:prototype];
}
- (EmptyBuilder*) builder {
  return [Empty builder];
}
- (EmptyBuilder*) toBuilder {
  return [Empty builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[Empty class]]) {
    return NO;
  }
  Empty *otherMessage = other;
  return
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface EmptyBuilder()
@property (strong) Empty* resultEmpty;
@end

@implementation EmptyBuilder
@synthesize resultEmpty;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultEmpty = [[Empty alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultEmpty;
}
- (EmptyBuilder*) clear {
  self.resultEmpty = [[Empty alloc] init];
  return self;
}
- (EmptyBuilder*) clone {
  return [Empty builderWithPrototype:resultEmpty];
}
- (Empty*) defaultInstance {
  return [Empty defaultInstance];
}
- (Empty*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (Empty*) buildPartial {
  Empty* returnMe = resultEmpty;
  self.resultEmpty = nil;
  return returnMe;
}
- (EmptyBuilder*) mergeFrom:(Empty*) other {
  if (other == [Empty defaultInstance]) {
    return self;
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (EmptyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (EmptyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
    }
  }
}
@end


// @@protoc_insertion_point(global_scope)
