// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Empty;
@class EmptyBuilder;



@interface EmptyRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Empty : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
}

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EmptyBuilder*) builder;
+ (EmptyBuilder*) builder;
+ (EmptyBuilder*) builderWithPrototype:(Empty*) prototype;
- (EmptyBuilder*) toBuilder;

+ (Empty*) parseFromData:(NSData*) data;
+ (Empty*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Empty*) parseFromInputStream:(NSInputStream*) input;
+ (Empty*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Empty*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Empty*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EmptyBuilder : PBGeneratedMessageBuilder {
@private
  Empty* resultEmpty;
}

- (Empty*) defaultInstance;

- (EmptyBuilder*) clear;
- (EmptyBuilder*) clone;

- (Empty*) build;
- (Empty*) buildPartial;

- (EmptyBuilder*) mergeFrom:(Empty*) other;
- (EmptyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EmptyBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end


// @@protoc_insertion_point(global_scope)
