// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class FieldMask;
@class FieldMaskBuilder;



@interface FieldMaskRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FieldMask_paths @"paths"
@interface FieldMask : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * pathsArray;
}
@property (readonly, strong) NSArray * paths;
- (NSString*)pathsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FieldMaskBuilder*) builder;
+ (FieldMaskBuilder*) builder;
+ (FieldMaskBuilder*) builderWithPrototype:(FieldMask*) prototype;
- (FieldMaskBuilder*) toBuilder;

+ (FieldMask*) parseFromData:(NSData*) data;
+ (FieldMask*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FieldMask*) parseFromInputStream:(NSInputStream*) input;
+ (FieldMask*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FieldMask*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FieldMask*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FieldMaskBuilder : PBGeneratedMessageBuilder {
@private
  FieldMask* resultFieldMask;
}

- (FieldMask*) defaultInstance;

- (FieldMaskBuilder*) clear;
- (FieldMaskBuilder*) clone;

- (FieldMask*) build;
- (FieldMask*) buildPartial;

- (FieldMaskBuilder*) mergeFrom:(FieldMask*) other;
- (FieldMaskBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FieldMaskBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)paths;
- (NSString*)pathsAtIndex:(NSUInteger)index;
- (FieldMaskBuilder *)addPaths:(NSString*)value;
- (FieldMaskBuilder *)setPathsArray:(NSArray *)array;
- (FieldMaskBuilder *)clearPaths;
@end


// @@protoc_insertion_point(global_scope)
