// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ListValue;
@class ListValueBuilder;
@class Struct;
@class StructBuilder;
@class StructFieldsEntry;
@class StructFieldsEntryBuilder;
@class Value;
@class ValueBuilder;


typedef NS_ENUM(SInt32, NullValue) {
  NullValueNullValue = 0,
};

BOOL NullValueIsValidValue(NullValue value);
NSString *NSStringFromNullValue(NullValue value);


@interface StructRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Struct_fields @"fields"
@interface Struct : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * fieldsArray;
}
@property (readonly, strong) NSArray<StructFieldsEntry*> * fields;
- (StructFieldsEntry*)fieldsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StructBuilder*) builder;
+ (StructBuilder*) builder;
+ (StructBuilder*) builderWithPrototype:(Struct*) prototype;
- (StructBuilder*) toBuilder;

+ (Struct*) parseFromData:(NSData*) data;
+ (Struct*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Struct*) parseFromInputStream:(NSInputStream*) input;
+ (Struct*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Struct*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Struct*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define FieldsEntry_key @"key"
#define FieldsEntry_value @"value"
@interface StructFieldsEntry : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  NSString* key;
  Value* value;
}
- (BOOL) hasKey;
- (BOOL) hasValue;
@property (readonly, strong) NSString* key;
@property (readonly, strong) Value* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StructFieldsEntryBuilder*) builder;
+ (StructFieldsEntryBuilder*) builder;
+ (StructFieldsEntryBuilder*) builderWithPrototype:(StructFieldsEntry*) prototype;
- (StructFieldsEntryBuilder*) toBuilder;

+ (StructFieldsEntry*) parseFromData:(NSData*) data;
+ (StructFieldsEntry*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StructFieldsEntry*) parseFromInputStream:(NSInputStream*) input;
+ (StructFieldsEntry*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StructFieldsEntry*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StructFieldsEntry*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StructFieldsEntryBuilder : PBGeneratedMessageBuilder {
@private
  StructFieldsEntry* resultFieldsEntry;
}

- (StructFieldsEntry*) defaultInstance;

- (StructFieldsEntryBuilder*) clear;
- (StructFieldsEntryBuilder*) clone;

- (StructFieldsEntry*) build;
- (StructFieldsEntry*) buildPartial;

- (StructFieldsEntryBuilder*) mergeFrom:(StructFieldsEntry*) other;
- (StructFieldsEntryBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StructFieldsEntryBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKey;
- (NSString*) key;
- (StructFieldsEntryBuilder*) setKey:(NSString*) value;
- (StructFieldsEntryBuilder*) clearKey;

- (BOOL) hasValue;
- (Value*) value;
- (StructFieldsEntryBuilder*) setValue:(Value*) value;
- (StructFieldsEntryBuilder*) setValueBuilder:(ValueBuilder*) builderForValue;
- (StructFieldsEntryBuilder*) mergeValue:(Value*) value;
- (StructFieldsEntryBuilder*) clearValue;
@end

@interface StructBuilder : PBGeneratedMessageBuilder {
@private
  Struct* resultStruct;
}

- (Struct*) defaultInstance;

- (StructBuilder*) clear;
- (StructBuilder*) clone;

- (Struct*) build;
- (Struct*) buildPartial;

- (StructBuilder*) mergeFrom:(Struct*) other;
- (StructBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StructBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<StructFieldsEntry*> *)fields;
- (StructFieldsEntry*)fieldsAtIndex:(NSUInteger)index;
- (StructBuilder *)addFields:(StructFieldsEntry*)value;
- (StructBuilder *)setFieldsArray:(NSArray<StructFieldsEntry*> *)array;
- (StructBuilder *)clearFields;
@end

#define Value_null_value @"nullValue"
#define Value_number_value @"numberValue"
#define Value_string_value @"stringValue"
#define Value_bool_value @"boolValue"
#define Value_struct_value @"structValue"
#define Value_list_value @"listValue"
@interface Value : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasBoolValue_:1;
  BOOL hasNumberValue_:1;
  BOOL hasStringValue_:1;
  BOOL hasStructValue_:1;
  BOOL hasListValue_:1;
  BOOL hasNullValue_:1;
  BOOL boolValue_:1;
  Float64 numberValue;
  NSString* stringValue;
  Struct* structValue;
  ListValue* listValue;
  NullValue nullValue;
}
- (BOOL) hasNullValue;
- (BOOL) hasNumberValue;
- (BOOL) hasStringValue;
- (BOOL) hasBoolValue;
- (BOOL) hasStructValue;
- (BOOL) hasListValue;
@property (readonly) NullValue nullValue;
@property (readonly) Float64 numberValue;
@property (readonly, strong) NSString* stringValue;
- (BOOL) boolValue;
@property (readonly, strong) Struct* structValue;
@property (readonly, strong) ListValue* listValue;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ValueBuilder*) builder;
+ (ValueBuilder*) builder;
+ (ValueBuilder*) builderWithPrototype:(Value*) prototype;
- (ValueBuilder*) toBuilder;

+ (Value*) parseFromData:(NSData*) data;
+ (Value*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Value*) parseFromInputStream:(NSInputStream*) input;
+ (Value*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Value*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Value*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ValueBuilder : PBGeneratedMessageBuilder {
@private
  Value* resultValue;
}

- (Value*) defaultInstance;

- (ValueBuilder*) clear;
- (ValueBuilder*) clone;

- (Value*) build;
- (Value*) buildPartial;

- (ValueBuilder*) mergeFrom:(Value*) other;
- (ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNullValue;
- (NullValue) nullValue;
- (ValueBuilder*) setNullValue:(NullValue) value;
- (ValueBuilder*) clearNullValue;

- (BOOL) hasNumberValue;
- (Float64) numberValue;
- (ValueBuilder*) setNumberValue:(Float64) value;
- (ValueBuilder*) clearNumberValue;

- (BOOL) hasStringValue;
- (NSString*) stringValue;
- (ValueBuilder*) setStringValue:(NSString*) value;
- (ValueBuilder*) clearStringValue;

- (BOOL) hasBoolValue;
- (BOOL) boolValue;
- (ValueBuilder*) setBoolValue:(BOOL) value;
- (ValueBuilder*) clearBoolValue;

- (BOOL) hasStructValue;
- (Struct*) structValue;
- (ValueBuilder*) setStructValue:(Struct*) value;
- (ValueBuilder*) setStructValueBuilder:(StructBuilder*) builderForValue;
- (ValueBuilder*) mergeStructValue:(Struct*) value;
- (ValueBuilder*) clearStructValue;

- (BOOL) hasListValue;
- (ListValue*) listValue;
- (ValueBuilder*) setListValue:(ListValue*) value;
- (ValueBuilder*) setListValueBuilder:(ListValueBuilder*) builderForValue;
- (ValueBuilder*) mergeListValue:(ListValue*) value;
- (ValueBuilder*) clearListValue;
@end

#define ListValue_values @"values"
@interface ListValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * valuesArray;
}
@property (readonly, strong) NSArray<Value*> * values;
- (Value*)valuesAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ListValueBuilder*) builder;
+ (ListValueBuilder*) builder;
+ (ListValueBuilder*) builderWithPrototype:(ListValue*) prototype;
- (ListValueBuilder*) toBuilder;

+ (ListValue*) parseFromData:(NSData*) data;
+ (ListValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ListValue*) parseFromInputStream:(NSInputStream*) input;
+ (ListValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ListValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ListValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ListValueBuilder : PBGeneratedMessageBuilder {
@private
  ListValue* resultListValue;
}

- (ListValue*) defaultInstance;

- (ListValueBuilder*) clear;
- (ListValueBuilder*) clone;

- (ListValue*) build;
- (ListValue*) buildPartial;

- (ListValueBuilder*) mergeFrom:(ListValue*) other;
- (ListValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ListValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<Value*> *)values;
- (Value*)valuesAtIndex:(NSUInteger)index;
- (ListValueBuilder *)addValues:(Value*)value;
- (ListValueBuilder *)setValuesArray:(NSArray<Value*> *)array;
- (ListValueBuilder *)clearValues;
@end


// @@protoc_insertion_point(global_scope)
