// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Timestamp;
@class TimestampBuilder;



@interface TimestampRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Timestamp_seconds @"seconds"
#define Timestamp_nanos @"nanos"
@interface Timestamp : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSeconds_:1;
  BOOL hasNanos_:1;
  SInt64 seconds;
  SInt32 nanos;
}
- (BOOL) hasSeconds;
- (BOOL) hasNanos;
@property (readonly) SInt64 seconds;
@property (readonly) SInt32 nanos;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TimestampBuilder*) builder;
+ (TimestampBuilder*) builder;
+ (TimestampBuilder*) builderWithPrototype:(Timestamp*) prototype;
- (TimestampBuilder*) toBuilder;

+ (Timestamp*) parseFromData:(NSData*) data;
+ (Timestamp*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Timestamp*) parseFromInputStream:(NSInputStream*) input;
+ (Timestamp*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Timestamp*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Timestamp*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TimestampBuilder : PBGeneratedMessageBuilder {
@private
  Timestamp* resultTimestamp;
}

- (Timestamp*) defaultInstance;

- (TimestampBuilder*) clear;
- (TimestampBuilder*) clone;

- (Timestamp*) build;
- (Timestamp*) buildPartial;

- (TimestampBuilder*) mergeFrom:(Timestamp*) other;
- (TimestampBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TimestampBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSeconds;
- (SInt64) seconds;
- (TimestampBuilder*) setSeconds:(SInt64) value;
- (TimestampBuilder*) clearSeconds;

- (BOOL) hasNanos;
- (SInt32) nanos;
- (TimestampBuilder*) setNanos:(SInt32) value;
- (TimestampBuilder*) clearNanos;
@end


// @@protoc_insertion_point(global_scope)
