// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "Any.pb.h"
#import "Source_context.pb.h"
// @@protoc_insertion_point(imports)

@class Any;
@class AnyBuilder;
@class Enum;
@class EnumBuilder;
@class EnumValue;
@class EnumValueBuilder;
@class Field;
@class FieldBuilder;
@class Option;
@class OptionBuilder;
@class SourceContext;
@class SourceContextBuilder;
@class Type;
@class TypeBuilder;


typedef NS_ENUM(SInt32, Syntax) {
  SyntaxSyntaxProto2 = 0,
  SyntaxSyntaxProto3 = 1,
};

BOOL SyntaxIsValidValue(Syntax value);
NSString *NSStringFromSyntax(Syntax value);

typedef NS_ENUM(SInt32, FieldKind) {
  FieldKindTypeUnknown = 0,
  FieldKindTypeDouble = 1,
  FieldKindTypeFloat = 2,
  FieldKindTypeInt64 = 3,
  FieldKindTypeUint64 = 4,
  FieldKindTypeInt32 = 5,
  FieldKindTypeFixed64 = 6,
  FieldKindTypeFixed32 = 7,
  FieldKindTypeBool = 8,
  FieldKindTypeString = 9,
  FieldKindTypeGroup = 10,
  FieldKindTypeMessage = 11,
  FieldKindTypeBytes = 12,
  FieldKindTypeUint32 = 13,
  FieldKindTypeEnum = 14,
  FieldKindTypeSfixed32 = 15,
  FieldKindTypeSfixed64 = 16,
  FieldKindTypeSint32 = 17,
  FieldKindTypeSint64 = 18,
};

BOOL FieldKindIsValidValue(FieldKind value);
NSString *NSStringFromFieldKind(FieldKind value);

typedef NS_ENUM(SInt32, FieldCardinality) {
  FieldCardinalityCardinalityUnknown = 0,
  FieldCardinalityCardinalityOptional = 1,
  FieldCardinalityCardinalityRequired = 2,
  FieldCardinalityCardinalityRepeated = 3,
};

BOOL FieldCardinalityIsValidValue(FieldCardinality value);
NSString *NSStringFromFieldCardinality(FieldCardinality value);


@interface TypeRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Type_name @"name"
#define Type_fields @"fields"
#define Type_oneofs @"oneofs"
#define Type_options @"options"
#define Type_source_context @"sourceContext"
#define Type_syntax @"syntax"
@interface Type : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasSourceContext_:1;
  BOOL hasSyntax_:1;
  NSString* name;
  SourceContext* sourceContext;
  Syntax syntax;
  NSMutableArray * oneofsArray;
  NSMutableArray * fieldsArray;
  NSMutableArray * optionsArray;
}
- (BOOL) hasName;
- (BOOL) hasSourceContext;
- (BOOL) hasSyntax;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSArray<Field*> * fields;
@property (readonly, strong) NSArray * oneofs;
@property (readonly, strong) NSArray<Option*> * options;
@property (readonly, strong) SourceContext* sourceContext;
@property (readonly) Syntax syntax;
- (Field*)fieldsAtIndex:(NSUInteger)index;
- (NSString*)oneofsAtIndex:(NSUInteger)index;
- (Option*)optionsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TypeBuilder*) builder;
+ (TypeBuilder*) builder;
+ (TypeBuilder*) builderWithPrototype:(Type*) prototype;
- (TypeBuilder*) toBuilder;

+ (Type*) parseFromData:(NSData*) data;
+ (Type*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Type*) parseFromInputStream:(NSInputStream*) input;
+ (Type*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Type*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Type*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TypeBuilder : PBGeneratedMessageBuilder {
@private
  Type* resultType;
}

- (Type*) defaultInstance;

- (TypeBuilder*) clear;
- (TypeBuilder*) clone;

- (Type*) build;
- (Type*) buildPartial;

- (TypeBuilder*) mergeFrom:(Type*) other;
- (TypeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TypeBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (TypeBuilder*) setName:(NSString*) value;
- (TypeBuilder*) clearName;

- (NSMutableArray<Field*> *)fields;
- (Field*)fieldsAtIndex:(NSUInteger)index;
- (TypeBuilder *)addFields:(Field*)value;
- (TypeBuilder *)setFieldsArray:(NSArray<Field*> *)array;
- (TypeBuilder *)clearFields;

- (NSMutableArray *)oneofs;
- (NSString*)oneofsAtIndex:(NSUInteger)index;
- (TypeBuilder *)addOneofs:(NSString*)value;
- (TypeBuilder *)setOneofsArray:(NSArray *)array;
- (TypeBuilder *)clearOneofs;

- (NSMutableArray<Option*> *)options;
- (Option*)optionsAtIndex:(NSUInteger)index;
- (TypeBuilder *)addOptions:(Option*)value;
- (TypeBuilder *)setOptionsArray:(NSArray<Option*> *)array;
- (TypeBuilder *)clearOptions;

- (BOOL) hasSourceContext;
- (SourceContext*) sourceContext;
- (TypeBuilder*) setSourceContext:(SourceContext*) value;
- (TypeBuilder*) setSourceContextBuilder:(SourceContextBuilder*) builderForValue;
- (TypeBuilder*) mergeSourceContext:(SourceContext*) value;
- (TypeBuilder*) clearSourceContext;

- (BOOL) hasSyntax;
- (Syntax) syntax;
- (TypeBuilder*) setSyntax:(Syntax) value;
- (TypeBuilder*) clearSyntax;
@end

#define Field_kind @"kind"
#define Field_cardinality @"cardinality"
#define Field_number @"number"
#define Field_name @"name"
#define Field_type_url @"typeUrl"
#define Field_oneof_index @"oneofIndex"
#define Field_packed @"packed"
#define Field_options @"options"
#define Field_json_name @"jsonName"
#define Field_default_value @"defaultValue"
@interface Field : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPacked_:1;
  BOOL hasNumber_:1;
  BOOL hasOneofIndex_:1;
  BOOL hasName_:1;
  BOOL hasTypeUrl_:1;
  BOOL hasJsonName_:1;
  BOOL hasDefaultValue_:1;
  BOOL hasKind_:1;
  BOOL hasCardinality_:1;
  BOOL packed_:1;
  SInt32 number;
  SInt32 oneofIndex;
  NSString* name;
  NSString* typeUrl;
  NSString* jsonName;
  NSString* defaultValue;
  FieldKind kind;
  FieldCardinality cardinality;
  NSMutableArray * optionsArray;
}
- (BOOL) hasKind;
- (BOOL) hasCardinality;
- (BOOL) hasNumber;
- (BOOL) hasName;
- (BOOL) hasTypeUrl;
- (BOOL) hasOneofIndex;
- (BOOL) hasPacked;
- (BOOL) hasJsonName;
- (BOOL) hasDefaultValue;
@property (readonly) FieldKind kind;
@property (readonly) FieldCardinality cardinality;
@property (readonly) SInt32 number;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* typeUrl;
@property (readonly) SInt32 oneofIndex;
- (BOOL) packed;
@property (readonly, strong) NSArray<Option*> * options;
@property (readonly, strong) NSString* jsonName;
@property (readonly, strong) NSString* defaultValue;
- (Option*)optionsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FieldBuilder*) builder;
+ (FieldBuilder*) builder;
+ (FieldBuilder*) builderWithPrototype:(Field*) prototype;
- (FieldBuilder*) toBuilder;

+ (Field*) parseFromData:(NSData*) data;
+ (Field*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Field*) parseFromInputStream:(NSInputStream*) input;
+ (Field*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Field*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Field*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FieldBuilder : PBGeneratedMessageBuilder {
@private
  Field* resultField;
}

- (Field*) defaultInstance;

- (FieldBuilder*) clear;
- (FieldBuilder*) clone;

- (Field*) build;
- (Field*) buildPartial;

- (FieldBuilder*) mergeFrom:(Field*) other;
- (FieldBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FieldBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKind;
- (FieldKind) kind;
- (FieldBuilder*) setKind:(FieldKind) value;
- (FieldBuilder*) clearKind;

- (BOOL) hasCardinality;
- (FieldCardinality) cardinality;
- (FieldBuilder*) setCardinality:(FieldCardinality) value;
- (FieldBuilder*) clearCardinality;

- (BOOL) hasNumber;
- (SInt32) number;
- (FieldBuilder*) setNumber:(SInt32) value;
- (FieldBuilder*) clearNumber;

- (BOOL) hasName;
- (NSString*) name;
- (FieldBuilder*) setName:(NSString*) value;
- (FieldBuilder*) clearName;

- (BOOL) hasTypeUrl;
- (NSString*) typeUrl;
- (FieldBuilder*) setTypeUrl:(NSString*) value;
- (FieldBuilder*) clearTypeUrl;

- (BOOL) hasOneofIndex;
- (SInt32) oneofIndex;
- (FieldBuilder*) setOneofIndex:(SInt32) value;
- (FieldBuilder*) clearOneofIndex;

- (BOOL) hasPacked;
- (BOOL) packed;
- (FieldBuilder*) setPacked:(BOOL) value;
- (FieldBuilder*) clearPacked;

- (NSMutableArray<Option*> *)options;
- (Option*)optionsAtIndex:(NSUInteger)index;
- (FieldBuilder *)addOptions:(Option*)value;
- (FieldBuilder *)setOptionsArray:(NSArray<Option*> *)array;
- (FieldBuilder *)clearOptions;

- (BOOL) hasJsonName;
- (NSString*) jsonName;
- (FieldBuilder*) setJsonName:(NSString*) value;
- (FieldBuilder*) clearJsonName;

- (BOOL) hasDefaultValue;
- (NSString*) defaultValue;
- (FieldBuilder*) setDefaultValue:(NSString*) value;
- (FieldBuilder*) clearDefaultValue;
@end

#define Enum_name @"name"
#define Enum_enumvalue @"enumvalue"
#define Enum_options @"options"
#define Enum_source_context @"sourceContext"
#define Enum_syntax @"syntax"
@interface Enum : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasSourceContext_:1;
  BOOL hasSyntax_:1;
  NSString* name;
  SourceContext* sourceContext;
  Syntax syntax;
  NSMutableArray * enumvalueArray;
  NSMutableArray * optionsArray;
}
- (BOOL) hasName;
- (BOOL) hasSourceContext;
- (BOOL) hasSyntax;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSArray<EnumValue*> * enumvalue;
@property (readonly, strong) NSArray<Option*> * options;
@property (readonly, strong) SourceContext* sourceContext;
@property (readonly) Syntax syntax;
- (EnumValue*)enumvalueAtIndex:(NSUInteger)index;
- (Option*)optionsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnumBuilder*) builder;
+ (EnumBuilder*) builder;
+ (EnumBuilder*) builderWithPrototype:(Enum*) prototype;
- (EnumBuilder*) toBuilder;

+ (Enum*) parseFromData:(NSData*) data;
+ (Enum*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Enum*) parseFromInputStream:(NSInputStream*) input;
+ (Enum*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Enum*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Enum*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnumBuilder : PBGeneratedMessageBuilder {
@private
  Enum* resultEnum;
}

- (Enum*) defaultInstance;

- (EnumBuilder*) clear;
- (EnumBuilder*) clone;

- (Enum*) build;
- (Enum*) buildPartial;

- (EnumBuilder*) mergeFrom:(Enum*) other;
- (EnumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnumBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (EnumBuilder*) setName:(NSString*) value;
- (EnumBuilder*) clearName;

- (NSMutableArray<EnumValue*> *)enumvalue;
- (EnumValue*)enumvalueAtIndex:(NSUInteger)index;
- (EnumBuilder *)addEnumvalue:(EnumValue*)value;
- (EnumBuilder *)setEnumvalueArray:(NSArray<EnumValue*> *)array;
- (EnumBuilder *)clearEnumvalue;

- (NSMutableArray<Option*> *)options;
- (Option*)optionsAtIndex:(NSUInteger)index;
- (EnumBuilder *)addOptions:(Option*)value;
- (EnumBuilder *)setOptionsArray:(NSArray<Option*> *)array;
- (EnumBuilder *)clearOptions;

- (BOOL) hasSourceContext;
- (SourceContext*) sourceContext;
- (EnumBuilder*) setSourceContext:(SourceContext*) value;
- (EnumBuilder*) setSourceContextBuilder:(SourceContextBuilder*) builderForValue;
- (EnumBuilder*) mergeSourceContext:(SourceContext*) value;
- (EnumBuilder*) clearSourceContext;

- (BOOL) hasSyntax;
- (Syntax) syntax;
- (EnumBuilder*) setSyntax:(Syntax) value;
- (EnumBuilder*) clearSyntax;
@end

#define EnumValue_name @"name"
#define EnumValue_number @"number"
#define EnumValue_options @"options"
@interface EnumValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasNumber_:1;
  BOOL hasName_:1;
  SInt32 number;
  NSString* name;
  NSMutableArray * optionsArray;
}
- (BOOL) hasName;
- (BOOL) hasNumber;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 number;
@property (readonly, strong) NSArray<Option*> * options;
- (Option*)optionsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnumValueBuilder*) builder;
+ (EnumValueBuilder*) builder;
+ (EnumValueBuilder*) builderWithPrototype:(EnumValue*) prototype;
- (EnumValueBuilder*) toBuilder;

+ (EnumValue*) parseFromData:(NSData*) data;
+ (EnumValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumValue*) parseFromInputStream:(NSInputStream*) input;
+ (EnumValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EnumValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnumValueBuilder : PBGeneratedMessageBuilder {
@private
  EnumValue* resultEnumValue;
}

- (EnumValue*) defaultInstance;

- (EnumValueBuilder*) clear;
- (EnumValueBuilder*) clone;

- (EnumValue*) build;
- (EnumValue*) buildPartial;

- (EnumValueBuilder*) mergeFrom:(EnumValue*) other;
- (EnumValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnumValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (EnumValueBuilder*) setName:(NSString*) value;
- (EnumValueBuilder*) clearName;

- (BOOL) hasNumber;
- (SInt32) number;
- (EnumValueBuilder*) setNumber:(SInt32) value;
- (EnumValueBuilder*) clearNumber;

- (NSMutableArray<Option*> *)options;
- (Option*)optionsAtIndex:(NSUInteger)index;
- (EnumValueBuilder *)addOptions:(Option*)value;
- (EnumValueBuilder *)setOptionsArray:(NSArray<Option*> *)array;
- (EnumValueBuilder *)clearOptions;
@end

#define Option_name @"name"
#define Option_value @"value"
@interface Option : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasName_:1;
  BOOL hasValue_:1;
  NSString* name;
  Any* value;
}
- (BOOL) hasName;
- (BOOL) hasValue;
@property (readonly, strong) NSString* name;
@property (readonly, strong) Any* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OptionBuilder*) builder;
+ (OptionBuilder*) builder;
+ (OptionBuilder*) builderWithPrototype:(Option*) prototype;
- (OptionBuilder*) toBuilder;

+ (Option*) parseFromData:(NSData*) data;
+ (Option*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Option*) parseFromInputStream:(NSInputStream*) input;
+ (Option*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Option*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Option*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OptionBuilder : PBGeneratedMessageBuilder {
@private
  Option* resultOption;
}

- (Option*) defaultInstance;

- (OptionBuilder*) clear;
- (OptionBuilder*) clone;

- (Option*) build;
- (Option*) buildPartial;

- (OptionBuilder*) mergeFrom:(Option*) other;
- (OptionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OptionBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (OptionBuilder*) setName:(NSString*) value;
- (OptionBuilder*) clearName;

- (BOOL) hasValue;
- (Any*) value;
- (OptionBuilder*) setValue:(Any*) value;
- (OptionBuilder*) setValueBuilder:(AnyBuilder*) builderForValue;
- (OptionBuilder*) mergeValue:(Any*) value;
- (OptionBuilder*) clearValue;
@end


// @@protoc_insertion_point(global_scope)
