// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class BoolValue;
@class BoolValueBuilder;
@class BytesValue;
@class BytesValueBuilder;
@class DoubleValue;
@class DoubleValueBuilder;
@class FloatValue;
@class FloatValueBuilder;
@class Int32Value;
@class Int32ValueBuilder;
@class Int64Value;
@class Int64ValueBuilder;
@class StringValue;
@class StringValueBuilder;
@class UInt32Value;
@class UInt32ValueBuilder;
@class UInt64Value;
@class UInt64ValueBuilder;



@interface WrappersRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define DoubleValue_value @"value"
@interface DoubleValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  Float64 value;
}
- (BOOL) hasValue;
@property (readonly) Float64 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DoubleValueBuilder*) builder;
+ (DoubleValueBuilder*) builder;
+ (DoubleValueBuilder*) builderWithPrototype:(DoubleValue*) prototype;
- (DoubleValueBuilder*) toBuilder;

+ (DoubleValue*) parseFromData:(NSData*) data;
+ (DoubleValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DoubleValue*) parseFromInputStream:(NSInputStream*) input;
+ (DoubleValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DoubleValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DoubleValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DoubleValueBuilder : PBGeneratedMessageBuilder {
@private
  DoubleValue* resultDoubleValue;
}

- (DoubleValue*) defaultInstance;

- (DoubleValueBuilder*) clear;
- (DoubleValueBuilder*) clone;

- (DoubleValue*) build;
- (DoubleValue*) buildPartial;

- (DoubleValueBuilder*) mergeFrom:(DoubleValue*) other;
- (DoubleValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DoubleValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (Float64) value;
- (DoubleValueBuilder*) setValue:(Float64) value;
- (DoubleValueBuilder*) clearValue;
@end

#define FloatValue_value @"value"
@interface FloatValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  Float32 value;
}
- (BOOL) hasValue;
@property (readonly) Float32 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FloatValueBuilder*) builder;
+ (FloatValueBuilder*) builder;
+ (FloatValueBuilder*) builderWithPrototype:(FloatValue*) prototype;
- (FloatValueBuilder*) toBuilder;

+ (FloatValue*) parseFromData:(NSData*) data;
+ (FloatValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FloatValue*) parseFromInputStream:(NSInputStream*) input;
+ (FloatValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FloatValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FloatValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FloatValueBuilder : PBGeneratedMessageBuilder {
@private
  FloatValue* resultFloatValue;
}

- (FloatValue*) defaultInstance;

- (FloatValueBuilder*) clear;
- (FloatValueBuilder*) clone;

- (FloatValue*) build;
- (FloatValue*) buildPartial;

- (FloatValueBuilder*) mergeFrom:(FloatValue*) other;
- (FloatValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FloatValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (Float32) value;
- (FloatValueBuilder*) setValue:(Float32) value;
- (FloatValueBuilder*) clearValue;
@end

#define Int64Value_value @"value"
@interface Int64Value : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  SInt64 value;
}
- (BOOL) hasValue;
@property (readonly) SInt64 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Int64ValueBuilder*) builder;
+ (Int64ValueBuilder*) builder;
+ (Int64ValueBuilder*) builderWithPrototype:(Int64Value*) prototype;
- (Int64ValueBuilder*) toBuilder;

+ (Int64Value*) parseFromData:(NSData*) data;
+ (Int64Value*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Int64Value*) parseFromInputStream:(NSInputStream*) input;
+ (Int64Value*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Int64Value*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Int64Value*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Int64ValueBuilder : PBGeneratedMessageBuilder {
@private
  Int64Value* resultInt64Value;
}

- (Int64Value*) defaultInstance;

- (Int64ValueBuilder*) clear;
- (Int64ValueBuilder*) clone;

- (Int64Value*) build;
- (Int64Value*) buildPartial;

- (Int64ValueBuilder*) mergeFrom:(Int64Value*) other;
- (Int64ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Int64ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (SInt64) value;
- (Int64ValueBuilder*) setValue:(SInt64) value;
- (Int64ValueBuilder*) clearValue;
@end

#define UInt64Value_value @"value"
@interface UInt64Value : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  UInt64 value;
}
- (BOOL) hasValue;
@property (readonly) UInt64 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UInt64ValueBuilder*) builder;
+ (UInt64ValueBuilder*) builder;
+ (UInt64ValueBuilder*) builderWithPrototype:(UInt64Value*) prototype;
- (UInt64ValueBuilder*) toBuilder;

+ (UInt64Value*) parseFromData:(NSData*) data;
+ (UInt64Value*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UInt64Value*) parseFromInputStream:(NSInputStream*) input;
+ (UInt64Value*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UInt64Value*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UInt64Value*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UInt64ValueBuilder : PBGeneratedMessageBuilder {
@private
  UInt64Value* resultUint64Value;
}

- (UInt64Value*) defaultInstance;

- (UInt64ValueBuilder*) clear;
- (UInt64ValueBuilder*) clone;

- (UInt64Value*) build;
- (UInt64Value*) buildPartial;

- (UInt64ValueBuilder*) mergeFrom:(UInt64Value*) other;
- (UInt64ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UInt64ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (UInt64) value;
- (UInt64ValueBuilder*) setValue:(UInt64) value;
- (UInt64ValueBuilder*) clearValue;
@end

#define Int32Value_value @"value"
@interface Int32Value : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  SInt32 value;
}
- (BOOL) hasValue;
@property (readonly) SInt32 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Int32ValueBuilder*) builder;
+ (Int32ValueBuilder*) builder;
+ (Int32ValueBuilder*) builderWithPrototype:(Int32Value*) prototype;
- (Int32ValueBuilder*) toBuilder;

+ (Int32Value*) parseFromData:(NSData*) data;
+ (Int32Value*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Int32Value*) parseFromInputStream:(NSInputStream*) input;
+ (Int32Value*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Int32Value*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Int32Value*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Int32ValueBuilder : PBGeneratedMessageBuilder {
@private
  Int32Value* resultInt32Value;
}

- (Int32Value*) defaultInstance;

- (Int32ValueBuilder*) clear;
- (Int32ValueBuilder*) clone;

- (Int32Value*) build;
- (Int32Value*) buildPartial;

- (Int32ValueBuilder*) mergeFrom:(Int32Value*) other;
- (Int32ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Int32ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (SInt32) value;
- (Int32ValueBuilder*) setValue:(SInt32) value;
- (Int32ValueBuilder*) clearValue;
@end

#define UInt32Value_value @"value"
@interface UInt32Value : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  UInt32 value;
}
- (BOOL) hasValue;
@property (readonly) UInt32 value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UInt32ValueBuilder*) builder;
+ (UInt32ValueBuilder*) builder;
+ (UInt32ValueBuilder*) builderWithPrototype:(UInt32Value*) prototype;
- (UInt32ValueBuilder*) toBuilder;

+ (UInt32Value*) parseFromData:(NSData*) data;
+ (UInt32Value*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UInt32Value*) parseFromInputStream:(NSInputStream*) input;
+ (UInt32Value*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UInt32Value*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UInt32Value*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UInt32ValueBuilder : PBGeneratedMessageBuilder {
@private
  UInt32Value* resultUint32Value;
}

- (UInt32Value*) defaultInstance;

- (UInt32ValueBuilder*) clear;
- (UInt32ValueBuilder*) clone;

- (UInt32Value*) build;
- (UInt32Value*) buildPartial;

- (UInt32ValueBuilder*) mergeFrom:(UInt32Value*) other;
- (UInt32ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UInt32ValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (UInt32) value;
- (UInt32ValueBuilder*) setValue:(UInt32) value;
- (UInt32ValueBuilder*) clearValue;
@end

#define BoolValue_value @"value"
@interface BoolValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  BOOL value_:1;
}
- (BOOL) hasValue;
- (BOOL) value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BoolValueBuilder*) builder;
+ (BoolValueBuilder*) builder;
+ (BoolValueBuilder*) builderWithPrototype:(BoolValue*) prototype;
- (BoolValueBuilder*) toBuilder;

+ (BoolValue*) parseFromData:(NSData*) data;
+ (BoolValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BoolValue*) parseFromInputStream:(NSInputStream*) input;
+ (BoolValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BoolValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BoolValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BoolValueBuilder : PBGeneratedMessageBuilder {
@private
  BoolValue* resultBoolValue;
}

- (BoolValue*) defaultInstance;

- (BoolValueBuilder*) clear;
- (BoolValueBuilder*) clone;

- (BoolValue*) build;
- (BoolValue*) buildPartial;

- (BoolValueBuilder*) mergeFrom:(BoolValue*) other;
- (BoolValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BoolValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (BOOL) value;
- (BoolValueBuilder*) setValue:(BOOL) value;
- (BoolValueBuilder*) clearValue;
@end

#define StringValue_value @"value"
@interface StringValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  NSString* value;
}
- (BOOL) hasValue;
@property (readonly, strong) NSString* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StringValueBuilder*) builder;
+ (StringValueBuilder*) builder;
+ (StringValueBuilder*) builderWithPrototype:(StringValue*) prototype;
- (StringValueBuilder*) toBuilder;

+ (StringValue*) parseFromData:(NSData*) data;
+ (StringValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StringValue*) parseFromInputStream:(NSInputStream*) input;
+ (StringValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StringValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StringValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StringValueBuilder : PBGeneratedMessageBuilder {
@private
  StringValue* resultStringValue;
}

- (StringValue*) defaultInstance;

- (StringValueBuilder*) clear;
- (StringValueBuilder*) clone;

- (StringValue*) build;
- (StringValue*) buildPartial;

- (StringValueBuilder*) mergeFrom:(StringValue*) other;
- (StringValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StringValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (NSString*) value;
- (StringValueBuilder*) setValue:(NSString*) value;
- (StringValueBuilder*) clearValue;
@end

#define BytesValue_value @"value"
@interface BytesValue : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasValue_:1;
  NSData* value;
}
- (BOOL) hasValue;
@property (readonly, strong) NSData* value;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BytesValueBuilder*) builder;
+ (BytesValueBuilder*) builder;
+ (BytesValueBuilder*) builderWithPrototype:(BytesValue*) prototype;
- (BytesValueBuilder*) toBuilder;

+ (BytesValue*) parseFromData:(NSData*) data;
+ (BytesValue*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BytesValue*) parseFromInputStream:(NSInputStream*) input;
+ (BytesValue*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BytesValue*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BytesValue*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BytesValueBuilder : PBGeneratedMessageBuilder {
@private
  BytesValue* resultBytesValue;
}

- (BytesValue*) defaultInstance;

- (BytesValueBuilder*) clear;
- (BytesValueBuilder*) clone;

- (BytesValue*) build;
- (BytesValue*) buildPartial;

- (BytesValueBuilder*) mergeFrom:(BytesValue*) other;
- (BytesValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BytesValueBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasValue;
- (NSData*) value;
- (BytesValueBuilder*) setValue:(NSData*) value;
- (BytesValueBuilder*) clearValue;
@end


// @@protoc_insertion_point(global_scope)
