// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/objectivec-descriptor.proto

#ifndef PROTOBUF_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto__INCLUDED
#define PROTOBUF_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace protobuf {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();
void protobuf_AssignDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();
void protobuf_ShutdownFile_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();

class ObjectiveCFileOptions;

// ===================================================================

class ObjectiveCFileOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.protobuf.ObjectiveCFileOptions) */ {
 public:
  ObjectiveCFileOptions();
  virtual ~ObjectiveCFileOptions();

  ObjectiveCFileOptions(const ObjectiveCFileOptions& from);

  inline ObjectiveCFileOptions& operator=(const ObjectiveCFileOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ObjectiveCFileOptions& default_instance();

  void Swap(ObjectiveCFileOptions* other);

  // implements Message ----------------------------------------------

  inline ObjectiveCFileOptions* New() const { return New(NULL); }

  ObjectiveCFileOptions* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ObjectiveCFileOptions& from);
  void MergeFrom(const ObjectiveCFileOptions& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ObjectiveCFileOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string package = 1;
  bool has_package() const;
  void clear_package();
  static const int kPackageFieldNumber = 1;
  const ::std::string& package() const;
  void set_package(const ::std::string& value);
  void set_package(const char* value);
  void set_package(const char* value, size_t size);
  ::std::string* mutable_package();
  ::std::string* release_package();
  void set_allocated_package(::std::string* package);

  // optional string class_prefix = 2;
  bool has_class_prefix() const;
  void clear_class_prefix();
  static const int kClassPrefixFieldNumber = 2;
  const ::std::string& class_prefix() const;
  void set_class_prefix(const ::std::string& value);
  void set_class_prefix(const char* value);
  void set_class_prefix(const char* value, size_t size);
  ::std::string* mutable_class_prefix();
  ::std::string* release_class_prefix();
  void set_allocated_class_prefix(::std::string* class_prefix);

  // optional bool relax_camel_case = 3;
  bool has_relax_camel_case() const;
  void clear_relax_camel_case();
  static const int kRelaxCamelCaseFieldNumber = 3;
  bool relax_camel_case() const;
  void set_relax_camel_case(bool value);

  // @@protoc_insertion_point(class_scope:google.protobuf.ObjectiveCFileOptions)
 private:
  inline void set_has_package();
  inline void clear_has_package();
  inline void set_has_class_prefix();
  inline void clear_has_class_prefix();
  inline void set_has_relax_camel_case();
  inline void clear_has_relax_camel_case();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr package_;
  ::google::protobuf::internal::ArenaStringPtr class_prefix_;
  bool relax_camel_case_;
  friend void  protobuf_AddDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();

  void InitAsDefaultInstance();
  static ObjectiveCFileOptions* default_instance_;
};
// ===================================================================

static const int kObjectivecFileOptionsFieldNumber = 1002;
extern ::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::google::protobuf::ObjectiveCFileOptions >, 11, false >
  objectivec_file_options;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ObjectiveCFileOptions

// optional string package = 1;
inline bool ObjectiveCFileOptions::has_package() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ObjectiveCFileOptions::set_has_package() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ObjectiveCFileOptions::clear_has_package() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ObjectiveCFileOptions::clear_package() {
  package_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_package();
}
inline const ::std::string& ObjectiveCFileOptions::package() const {
  // @@protoc_insertion_point(field_get:google.protobuf.ObjectiveCFileOptions.package)
  return package_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ObjectiveCFileOptions::set_package(const ::std::string& value) {
  set_has_package();
  package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.ObjectiveCFileOptions.package)
}
inline void ObjectiveCFileOptions::set_package(const char* value) {
  set_has_package();
  package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.ObjectiveCFileOptions.package)
}
inline void ObjectiveCFileOptions::set_package(const char* value, size_t size) {
  set_has_package();
  package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.ObjectiveCFileOptions.package)
}
inline ::std::string* ObjectiveCFileOptions::mutable_package() {
  set_has_package();
  // @@protoc_insertion_point(field_mutable:google.protobuf.ObjectiveCFileOptions.package)
  return package_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ObjectiveCFileOptions::release_package() {
  // @@protoc_insertion_point(field_release:google.protobuf.ObjectiveCFileOptions.package)
  clear_has_package();
  return package_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ObjectiveCFileOptions::set_allocated_package(::std::string* package) {
  if (package != NULL) {
    set_has_package();
  } else {
    clear_has_package();
  }
  package_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), package);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.ObjectiveCFileOptions.package)
}

// optional string class_prefix = 2;
inline bool ObjectiveCFileOptions::has_class_prefix() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ObjectiveCFileOptions::set_has_class_prefix() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ObjectiveCFileOptions::clear_has_class_prefix() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ObjectiveCFileOptions::clear_class_prefix() {
  class_prefix_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_class_prefix();
}
inline const ::std::string& ObjectiveCFileOptions::class_prefix() const {
  // @@protoc_insertion_point(field_get:google.protobuf.ObjectiveCFileOptions.class_prefix)
  return class_prefix_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ObjectiveCFileOptions::set_class_prefix(const ::std::string& value) {
  set_has_class_prefix();
  class_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.ObjectiveCFileOptions.class_prefix)
}
inline void ObjectiveCFileOptions::set_class_prefix(const char* value) {
  set_has_class_prefix();
  class_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.ObjectiveCFileOptions.class_prefix)
}
inline void ObjectiveCFileOptions::set_class_prefix(const char* value, size_t size) {
  set_has_class_prefix();
  class_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.ObjectiveCFileOptions.class_prefix)
}
inline ::std::string* ObjectiveCFileOptions::mutable_class_prefix() {
  set_has_class_prefix();
  // @@protoc_insertion_point(field_mutable:google.protobuf.ObjectiveCFileOptions.class_prefix)
  return class_prefix_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ObjectiveCFileOptions::release_class_prefix() {
  // @@protoc_insertion_point(field_release:google.protobuf.ObjectiveCFileOptions.class_prefix)
  clear_has_class_prefix();
  return class_prefix_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ObjectiveCFileOptions::set_allocated_class_prefix(::std::string* class_prefix) {
  if (class_prefix != NULL) {
    set_has_class_prefix();
  } else {
    clear_has_class_prefix();
  }
  class_prefix_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), class_prefix);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.ObjectiveCFileOptions.class_prefix)
}

// optional bool relax_camel_case = 3;
inline bool ObjectiveCFileOptions::has_relax_camel_case() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ObjectiveCFileOptions::set_has_relax_camel_case() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ObjectiveCFileOptions::clear_has_relax_camel_case() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ObjectiveCFileOptions::clear_relax_camel_case() {
  relax_camel_case_ = false;
  clear_has_relax_camel_case();
}
inline bool ObjectiveCFileOptions::relax_camel_case() const {
  // @@protoc_insertion_point(field_get:google.protobuf.ObjectiveCFileOptions.relax_camel_case)
  return relax_camel_case_;
}
inline void ObjectiveCFileOptions::set_relax_camel_case(bool value) {
  set_has_relax_camel_case();
  relax_camel_case_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.ObjectiveCFileOptions.relax_camel_case)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto__INCLUDED
