// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/objectivec-descriptor.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include <google/protobuf/objectivec-descriptor.pb.h>

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace google {
namespace protobuf {

namespace {

const ::google::protobuf::Descriptor* ObjectiveCFileOptions_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ObjectiveCFileOptions_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto() {
  protobuf_AddDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "google/protobuf/objectivec-descriptor.proto");
  GOOGLE_CHECK(file != NULL);
  ObjectiveCFileOptions_descriptor_ = file->message_type(0);
  static const int ObjectiveCFileOptions_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectiveCFileOptions, package_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectiveCFileOptions, class_prefix_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectiveCFileOptions, relax_camel_case_),
  };
  ObjectiveCFileOptions_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ObjectiveCFileOptions_descriptor_,
      ObjectiveCFileOptions::default_instance_,
      ObjectiveCFileOptions_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectiveCFileOptions, _has_bits_[0]),
      -1,
      -1,
      sizeof(ObjectiveCFileOptions),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ObjectiveCFileOptions, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ObjectiveCFileOptions_descriptor_, &ObjectiveCFileOptions::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto() {
  delete ObjectiveCFileOptions::default_instance_;
  delete ObjectiveCFileOptions_reflection_;
}

void protobuf_AddDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n+google/protobuf/objectivec-descriptor."
    "proto\022\017google.protobuf\032 google/protobuf/"
    "descriptor.proto\"X\n\025ObjectiveCFileOption"
    "s\022\017\n\007package\030\001 \001(\t\022\024\n\014class_prefix\030\002 \001(\t"
    "\022\030\n\020relax_camel_case\030\003 \001(\010:f\n\027objectivec"
    "_file_options\022\034.google.protobuf.FileOpti"
    "ons\030\352\007 \001(\0132&.google.protobuf.ObjectiveCF"
    "ileOptions", 290);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "google/protobuf/objectivec-descriptor.proto", &protobuf_RegisterTypes);
  ObjectiveCFileOptions::default_instance_ = new ObjectiveCFileOptions();
  ::google::protobuf::internal::ExtensionSet::RegisterMessageExtension(
    &::google::protobuf::FileOptions::default_instance(),
    1002, 11, false, false,
    &::google::protobuf::ObjectiveCFileOptions::default_instance());
  ObjectiveCFileOptions::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto {
  StaticDescriptorInitializer_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto() {
    protobuf_AddDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();
  }
} static_descriptor_initializer_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ObjectiveCFileOptions::kPackageFieldNumber;
const int ObjectiveCFileOptions::kClassPrefixFieldNumber;
const int ObjectiveCFileOptions::kRelaxCamelCaseFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ObjectiveCFileOptions::ObjectiveCFileOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.ObjectiveCFileOptions)
}

void ObjectiveCFileOptions::InitAsDefaultInstance() {
}

ObjectiveCFileOptions::ObjectiveCFileOptions(const ObjectiveCFileOptions& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:google.protobuf.ObjectiveCFileOptions)
}

void ObjectiveCFileOptions::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  package_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  class_prefix_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  relax_camel_case_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ObjectiveCFileOptions::~ObjectiveCFileOptions() {
  // @@protoc_insertion_point(destructor:google.protobuf.ObjectiveCFileOptions)
  SharedDtor();
}

void ObjectiveCFileOptions::SharedDtor() {
  package_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  class_prefix_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void ObjectiveCFileOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ObjectiveCFileOptions::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ObjectiveCFileOptions_descriptor_;
}

const ObjectiveCFileOptions& ObjectiveCFileOptions::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_google_2fprotobuf_2fobjectivec_2ddescriptor_2eproto();
  return *default_instance_;
}

ObjectiveCFileOptions* ObjectiveCFileOptions::default_instance_ = NULL;

ObjectiveCFileOptions* ObjectiveCFileOptions::New(::google::protobuf::Arena* arena) const {
  ObjectiveCFileOptions* n = new ObjectiveCFileOptions;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ObjectiveCFileOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.ObjectiveCFileOptions)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_package()) {
      package_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_class_prefix()) {
      class_prefix_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    relax_camel_case_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ObjectiveCFileOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.ObjectiveCFileOptions)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string package = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_package()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->package().data(), this->package().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "google.protobuf.ObjectiveCFileOptions.package");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_class_prefix;
        break;
      }

      // optional string class_prefix = 2;
      case 2: {
        if (tag == 18) {
         parse_class_prefix:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_class_prefix()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->class_prefix().data(), this->class_prefix().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "google.protobuf.ObjectiveCFileOptions.class_prefix");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_relax_camel_case;
        break;
      }

      // optional bool relax_camel_case = 3;
      case 3: {
        if (tag == 24) {
         parse_relax_camel_case:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &relax_camel_case_)));
          set_has_relax_camel_case();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.ObjectiveCFileOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.ObjectiveCFileOptions)
  return false;
#undef DO_
}

void ObjectiveCFileOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.ObjectiveCFileOptions)
  // optional string package = 1;
  if (has_package()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->package().data(), this->package().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "google.protobuf.ObjectiveCFileOptions.package");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->package(), output);
  }

  // optional string class_prefix = 2;
  if (has_class_prefix()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->class_prefix().data(), this->class_prefix().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "google.protobuf.ObjectiveCFileOptions.class_prefix");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->class_prefix(), output);
  }

  // optional bool relax_camel_case = 3;
  if (has_relax_camel_case()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->relax_camel_case(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.ObjectiveCFileOptions)
}

::google::protobuf::uint8* ObjectiveCFileOptions::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.ObjectiveCFileOptions)
  // optional string package = 1;
  if (has_package()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->package().data(), this->package().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "google.protobuf.ObjectiveCFileOptions.package");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->package(), target);
  }

  // optional string class_prefix = 2;
  if (has_class_prefix()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->class_prefix().data(), this->class_prefix().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "google.protobuf.ObjectiveCFileOptions.class_prefix");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->class_prefix(), target);
  }

  // optional bool relax_camel_case = 3;
  if (has_relax_camel_case()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->relax_camel_case(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.ObjectiveCFileOptions)
  return target;
}

int ObjectiveCFileOptions::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.ObjectiveCFileOptions)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7u) {
    // optional string package = 1;
    if (has_package()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->package());
    }

    // optional string class_prefix = 2;
    if (has_class_prefix()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->class_prefix());
    }

    // optional bool relax_camel_case = 3;
    if (has_relax_camel_case()) {
      total_size += 1 + 1;
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ObjectiveCFileOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.ObjectiveCFileOptions)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const ObjectiveCFileOptions* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ObjectiveCFileOptions>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.ObjectiveCFileOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.ObjectiveCFileOptions)
    MergeFrom(*source);
  }
}

void ObjectiveCFileOptions::MergeFrom(const ObjectiveCFileOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.ObjectiveCFileOptions)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_package()) {
      set_has_package();
      package_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.package_);
    }
    if (from.has_class_prefix()) {
      set_has_class_prefix();
      class_prefix_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.class_prefix_);
    }
    if (from.has_relax_camel_case()) {
      set_relax_camel_case(from.relax_camel_case());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void ObjectiveCFileOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.ObjectiveCFileOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ObjectiveCFileOptions::CopyFrom(const ObjectiveCFileOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.ObjectiveCFileOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ObjectiveCFileOptions::IsInitialized() const {

  return true;
}

void ObjectiveCFileOptions::Swap(ObjectiveCFileOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ObjectiveCFileOptions::InternalSwap(ObjectiveCFileOptions* other) {
  package_.Swap(&other->package_);
  class_prefix_.Swap(&other->class_prefix_);
  std::swap(relax_camel_case_, other->relax_camel_case_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ObjectiveCFileOptions::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ObjectiveCFileOptions_descriptor_;
  metadata.reflection = ObjectiveCFileOptions_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ObjectiveCFileOptions

// optional string package = 1;
bool ObjectiveCFileOptions::has_package() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ObjectiveCFileOptions::set_has_package() {
  _has_bits_[0] |= 0x00000001u;
}
void ObjectiveCFileOptions::clear_has_package() {
  _has_bits_[0] &= ~0x00000001u;
}
void ObjectiveCFileOptions::clear_package() {
  package_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_package();
}
 const ::std::string& ObjectiveCFileOptions::package() const {
  // @@protoc_insertion_point(field_get:google.protobuf.ObjectiveCFileOptions.package)
  return package_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ObjectiveCFileOptions::set_package(const ::std::string& value) {
  set_has_package();
  package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.ObjectiveCFileOptions.package)
}
 void ObjectiveCFileOptions::set_package(const char* value) {
  set_has_package();
  package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.ObjectiveCFileOptions.package)
}
 void ObjectiveCFileOptions::set_package(const char* value, size_t size) {
  set_has_package();
  package_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.ObjectiveCFileOptions.package)
}
 ::std::string* ObjectiveCFileOptions::mutable_package() {
  set_has_package();
  // @@protoc_insertion_point(field_mutable:google.protobuf.ObjectiveCFileOptions.package)
  return package_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ObjectiveCFileOptions::release_package() {
  // @@protoc_insertion_point(field_release:google.protobuf.ObjectiveCFileOptions.package)
  clear_has_package();
  return package_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ObjectiveCFileOptions::set_allocated_package(::std::string* package) {
  if (package != NULL) {
    set_has_package();
  } else {
    clear_has_package();
  }
  package_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), package);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.ObjectiveCFileOptions.package)
}

// optional string class_prefix = 2;
bool ObjectiveCFileOptions::has_class_prefix() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ObjectiveCFileOptions::set_has_class_prefix() {
  _has_bits_[0] |= 0x00000002u;
}
void ObjectiveCFileOptions::clear_has_class_prefix() {
  _has_bits_[0] &= ~0x00000002u;
}
void ObjectiveCFileOptions::clear_class_prefix() {
  class_prefix_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_class_prefix();
}
 const ::std::string& ObjectiveCFileOptions::class_prefix() const {
  // @@protoc_insertion_point(field_get:google.protobuf.ObjectiveCFileOptions.class_prefix)
  return class_prefix_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ObjectiveCFileOptions::set_class_prefix(const ::std::string& value) {
  set_has_class_prefix();
  class_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:google.protobuf.ObjectiveCFileOptions.class_prefix)
}
 void ObjectiveCFileOptions::set_class_prefix(const char* value) {
  set_has_class_prefix();
  class_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:google.protobuf.ObjectiveCFileOptions.class_prefix)
}
 void ObjectiveCFileOptions::set_class_prefix(const char* value, size_t size) {
  set_has_class_prefix();
  class_prefix_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:google.protobuf.ObjectiveCFileOptions.class_prefix)
}
 ::std::string* ObjectiveCFileOptions::mutable_class_prefix() {
  set_has_class_prefix();
  // @@protoc_insertion_point(field_mutable:google.protobuf.ObjectiveCFileOptions.class_prefix)
  return class_prefix_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* ObjectiveCFileOptions::release_class_prefix() {
  // @@protoc_insertion_point(field_release:google.protobuf.ObjectiveCFileOptions.class_prefix)
  clear_has_class_prefix();
  return class_prefix_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ObjectiveCFileOptions::set_allocated_class_prefix(::std::string* class_prefix) {
  if (class_prefix != NULL) {
    set_has_class_prefix();
  } else {
    clear_has_class_prefix();
  }
  class_prefix_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), class_prefix);
  // @@protoc_insertion_point(field_set_allocated:google.protobuf.ObjectiveCFileOptions.class_prefix)
}

// optional bool relax_camel_case = 3;
bool ObjectiveCFileOptions::has_relax_camel_case() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void ObjectiveCFileOptions::set_has_relax_camel_case() {
  _has_bits_[0] |= 0x00000004u;
}
void ObjectiveCFileOptions::clear_has_relax_camel_case() {
  _has_bits_[0] &= ~0x00000004u;
}
void ObjectiveCFileOptions::clear_relax_camel_case() {
  relax_camel_case_ = false;
  clear_has_relax_camel_case();
}
 bool ObjectiveCFileOptions::relax_camel_case() const {
  // @@protoc_insertion_point(field_get:google.protobuf.ObjectiveCFileOptions.relax_camel_case)
  return relax_camel_case_;
}
 void ObjectiveCFileOptions::set_relax_camel_case(bool value) {
  set_has_relax_camel_case();
  relax_camel_case_ = value;
  // @@protoc_insertion_point(field_set:google.protobuf.ObjectiveCFileOptions.relax_camel_case)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::MessageTypeTraits< ::google::protobuf::ObjectiveCFileOptions >, 11, false >
  objectivec_file_options(kObjectivecFileOptionsFieldNumber, ::google::protobuf::ObjectiveCFileOptions::default_instance());

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
